version: "3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "rusik"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes: 
      - ./pg:/var/lib/postgresql/data